# Generated by Django 3.2 on 2023-08-19 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rename_ingredient_recipe_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
