# Generated by Django 3.2 on 2023-09-04 11:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0010_alter_recipeingredient_ingredient"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorite",
            options={
                "ordering": ("id",),
                "verbose_name": "Избранный рецепт",
                "verbose_name_plural": "Избранные рецепты",
            },
        ),
    ]
